### ISSUE TITLE
Configuration directives require double "netflix" prefix

### ISSUE THREAD

**Issue by danveloper** [Netflix/edda-client#1]
https://github.com/Netflix/edda-client/blob/master/edda-client/src/main/java/com/netflix/ie/config/Configuration$.java#L29-30

https://github.com/Netflix/edda-client/blob/master/edda-client/src/main/java/com/netflix/edda/AwsClientFactory$.java#L50

These two pieces are in contention and require a system property prefix of "netflix.netflix.edda.aws"

**Comment by brharrington** [comment]
Closing, this project is essential maintenance only at this point.
